INSERT INTO state (nm_state, sg_uf)
VALUES
    ('Santa Catarina', 'SC'),
    ('Acre', 'AC'),
    ('Alagoas', 'AL'),
    ('Amapá', 'AP'),
    ('Amazonas', 'AM'),
    ('Bahia', 'BA'),
    ('Ceará', 'CE'),
    ('Distrito Federal', 'DF'),
    ('Espírito Santo', 'ES'),
    ('Goiás', 'GO'),
    ('Maranhão', 'MA'),
    ('Mato Grosso', 'MT'),
    ('Mato Grosso do Sul', 'MS'),
    ('Minas Gerais', 'MG'),
    ('Pará', 'PA'),
    ('Paraíba', 'PB'),
    ('Paraná', 'PR'),
    ('Pernambuco', 'PE'),
    ('Piauí', 'PI'),
    ('Rio de Janeiro', 'RJ'),
    ('Rio Grande do Norte', 'RN'),
    ('Rio Grande do Sul', 'RS'),
    ('Rondônia', 'RO'),
    ('Roraima', 'RR'),
    ('São Paulo', 'SP'),
    ('Sergipe', 'SE'),
    ('Tocantins', 'TO');

INSERT INTO city (nm_city, cod_state)
VALUES
    ('Blumenau', 1),
    ('Florianópolis', 1),
    ('Joinville', 1),
    ('São José', 1),
    ('Chapecó', 1),
    ('Criciúma', 1),
    ('Itajaí', 1),
    ('Jaraguá do Sul', 1),
    ('Lages', 1),
    ('Balneário Camboriú', 1),
    ('Brusque', 1);